import { useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';

type Invoice = { id: string; number: string; customerName?: string | null; total: string; paidAmount: string; paymentStatus: string; status: string; issuedAt: string; items: Array<{ productName: string; quantity: number }> };
type StockOption = { id: string; barcode: string; quantity: number; salePrice: string; product: { name: string; code: string }; brand: { name: string } };
const money = (value: string | number) => `${new Intl.NumberFormat('fa-IR').format(Number(value))} ریال`;
const labels: Record<string, string> = { paid: 'پرداخت کامل', partial: 'پرداخت ناقص', unpaid: 'پرداخت‌نشده', issued: 'صادرشده', voided: 'باطل‌شده' };

export function InvoicesPage() {
  const [rows, setRows] = useState<Invoice[]>([]); const [options, setOptions] = useState<StockOption[]>([]); const [selected, setSelected] = useState('');
  const [quantity, setQuantity] = useState('1'); const [customer, setCustomer] = useState(''); const [mobile, setMobile] = useState(''); const [discount, setDiscount] = useState(''); const [payAmount, setPayAmount] = useState(''); const [payMethod, setPayMethod] = useState('cash'); const [paying, setPaying] = useState<Invoice | null>(null); const [message, setMessage] = useState('');
  const load = () => api<{ data: Invoice[] }>('/invoices').then((result) => setRows(result.data)).catch((error: Error) => setMessage(error.message));
  useEffect(() => { void load(); void api<{ data: StockOption[] }>('/invoices/options').then((result) => setOptions(result.data)).catch((error: Error) => setMessage(error.message)); }, []);
  const selectedOption = options.find((item) => item.id === selected);
  const preview = useMemo(() => Math.max(0, Number(selectedOption?.salePrice ?? 0) * Math.max(0, Number(quantity) || 0) - (Number(discount) || 0)), [selectedOption, quantity, discount]);
  const create = async () => { if (!selected || !Number.isInteger(Number(quantity)) || Number(quantity) <= 0) return setMessage('قلم و تعداد صحیح الزامی است'); try { await api('/invoices', { method: 'POST', body: JSON.stringify({ customerName: customer || undefined, customerMobile: mobile || undefined, discount: discount || 0, items: [{ inventoryItemId: selected, quantity: Number(quantity), unitPrice: selectedOption?.salePrice ?? '0' }] }) }); setMessage('فاکتور صادر شد و موجودی در Ledger ثبت شد'); setCustomer(''); setMobile(''); setDiscount(''); setQuantity('1'); await load(); } catch (error) { setMessage((error as Error).message); } };
  const pay = async () => { if (!paying || !payAmount) return; try { await api(`/invoices/${paying.id}/pay`, { method: 'POST', body: JSON.stringify({ amount: payAmount, method: payMethod }) }); setMessage('پرداخت ثبت شد و Audit گردید'); setPaying(null); setPayAmount(''); await load(); } catch (error) { setMessage((error as Error).message); } };
  return <section><div className="page-title"><div><h1>فروش و فاکتورها</h1><p className="muted">صدور فاکتور، مصرف اتمیک موجودی و ثبت پرداخت</p></div><span className="count">{rows.length} فاکتور</span></div>{message && <div className="notice">{message}</div>}
    <div className="cards invoice-form"><div><h2>صدور فاکتور جدید</h2><select value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">انتخاب قلم موجودی</option>{options.filter((item) => item.quantity > 0).map((item) => <option key={item.id} value={item.id}>{item.product.name} · {item.brand.name} · موجودی {item.quantity}</option>)}</select><div className="form-grid"><input placeholder="نام مشتری (اختیاری)" value={customer} onChange={(event) => setCustomer(event.target.value)} /><input placeholder="موبایل (اختیاری)" value={mobile} onChange={(event) => setMobile(event.target.value)} /><input type="number" min="1" placeholder="تعداد" value={quantity} onChange={(event) => setQuantity(event.target.value)} /><input type="number" min="0" placeholder="تخفیف ریال" value={discount} onChange={(event) => setDiscount(event.target.value)} /></div><p className="muted">مبلغ قابل صدور: <strong>{money(preview)}</strong></p><button onClick={() => void create()}>صدور فاکتور</button></div></div>
    {paying && <div className="notice"><strong>ثبت پرداخت {paying.number}</strong><input type="number" min="1" placeholder="مبلغ پرداختی ریال" value={payAmount} onChange={(event) => setPayAmount(event.target.value)} /><select value={payMethod} onChange={(event) => setPayMethod(event.target.value)}><option value="cash">نقدی</option><option value="card">کارت</option><option value="transfer">واریز</option><option value="credit">اعتباری</option></select><button onClick={() => void pay()}>ثبت</button><button className="outline" onClick={() => setPaying(null)}>انصراف</button></div>}
    <div className="product-table"><div className="table-head invoice-head"><span>شماره</span><span>مشتری</span><span>اقلام</span><span>مبلغ</span><span>پرداخت</span><span>عملیات</span></div>{rows.map((invoice) => <div className="table-row invoice-row" key={invoice.id}><code>{invoice.number}</code><span>{invoice.customerName ?? 'مشتری حضوری'}</span><span>{invoice.items.length}</span><strong>{money(invoice.total)}</strong><span className={invoice.paymentStatus === 'paid' ? 'status-chip' : 'low-stock'}>{labels[invoice.paymentStatus] ?? invoice.paymentStatus}<small> · {money(invoice.paidAmount)}</small></span><span>{invoice.status === 'voided' ? labels.voided : <><button className="row-action" onClick={() => { setPaying(invoice); setPayAmount(String(Number(invoice.total) - Number(invoice.paidAmount))); }}>پرداخت</button> <button className="row-action" onClick={async () => { if (!window.confirm('فاکتور باطل شود؟')) return; await api(`/invoices/${invoice.id}/void`, { method: 'POST' }); await load(); }}>ابطال</button></>}</span></div>)}</div></section>;
}
