import { useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';

type Invoice = { id: string; number: string; customerName?: string | null; total: string; paidAmount: string; paymentStatus: string; status: string; issuedAt: string; items: Array<{ productName: string; quantity: number }> };
type StockOption = { id: string; barcode: string; quantity: number; salePrice: string; product: { name: string; code: string }; brand: { name: string } };
type DraftLine = { item: StockOption; quantity: number };
type CreatedInvoice = { number: string; publicToken: string };
const money = (value: string | number) => `${new Intl.NumberFormat('fa-IR').format(Number(value))} ریال`;
const labels: Record<string, string> = { paid: 'پرداخت کامل', partial: 'پرداخت بخشی', unpaid: 'پرداخت‌نشده', issued: 'صادرشده', voided: 'باطل‌شده' };

export function InvoicesPage() {
  const [rows, setRows] = useState<Invoice[]>([]); const [options, setOptions] = useState<StockOption[]>([]); const [search, setSearch] = useState('');
  const [lines, setLines] = useState<DraftLine[]>([]); const [quantity, setQuantity] = useState('1'); const [customer, setCustomer] = useState(''); const [mobile, setMobile] = useState(''); const [discount, setDiscount] = useState(''); const [payAmount, setPayAmount] = useState(''); const [payMethod, setPayMethod] = useState('cash'); const [paying, setPaying] = useState<Invoice | null>(null); const [created, setCreated] = useState<CreatedInvoice | null>(null); const [message, setMessage] = useState('');
  const load = () => api<{ data: Invoice[] }>('/invoices').then((result) => setRows(result.data)).catch((error: Error) => setMessage(error.message));
  useEffect(() => { void load(); void api<{ data: StockOption[] }>('/invoices/options').then((result) => setOptions(result.data)).catch((error: Error) => setMessage(error.message)); }, []);
  const candidates = useMemo(() => { const query = search.trim().toLocaleLowerCase(); return options.filter((item) => item.quantity > 0 && !lines.some((line) => line.item.id === item.id) && (!query || `${item.product.name} ${item.product.code} ${item.barcode} ${item.brand.name}`.toLocaleLowerCase().includes(query))).slice(0, 12); }, [options, search, lines]);
  const subtotal = lines.reduce((sum, line) => sum + Number(line.item.salePrice) * line.quantity, 0); const discountValue = Math.max(0, Number(discount) || 0); const total = Math.max(0, subtotal - discountValue);
  const addLine = (item: StockOption) => { const count = Number(quantity); if (!Number.isInteger(count) || count <= 0) return setMessage('تعداد باید عدد صحیح مثبت باشد'); if (count > item.quantity) return setMessage(`موجودی ${item.product.name} فقط ${item.quantity} عدد است`); setLines((current) => [...current, { item, quantity: count }]); setQuantity('1'); setSearch(''); setMessage(''); };
  const updateLine = (id: string, next: string) => setLines((current) => current.map((line) => line.item.id === id ? { ...line, quantity: Math.min(line.item.quantity, Math.max(1, Number(next) || 1)) } : line));
  const create = async () => { if (!lines.length) return setMessage('حداقل یک قلم برای فاکتور انتخاب کنید'); if (discountValue > subtotal) return setMessage('تخفیف نمی‌تواند از جمع اقلام بیشتر باشد'); try { const response = await api<{ data: { number: string; publicToken: string } }>('/invoices', { method: 'POST', body: JSON.stringify({ customerName: customer || undefined, customerMobile: mobile || undefined, discount: discountValue, items: lines.map((line) => ({ inventoryItemId: line.item.id, quantity: line.quantity, unitPrice: line.item.salePrice })) }) }); setCreated({ number: response.data.number, publicToken: response.data.publicToken }); setMessage('فاکتور صادر شد و موجودی در Ledger ثبت شد'); setLines([]); setCustomer(''); setMobile(''); setDiscount(''); setQuantity('1'); await load(); } catch (error) { setMessage((error as Error).message); } };
  const pay = async () => { if (!paying || !payAmount) return; try { await api(`/invoices/${paying.id}/pay`, { method: 'POST', body: JSON.stringify({ amount: payAmount, method: payMethod }) }); setMessage('پرداخت ثبت شد و Audit گردید'); setPaying(null); setPayAmount(''); await load(); } catch (error) { setMessage((error as Error).message); } };
  return <section><div className="page-title"><div><h1>فروش و فاکتورها</h1><p className="muted">صدور فاکتور چندقلمی، مصرف اتمیک موجودی و ثبت پرداخت</p></div><span className="count">{rows.length} فاکتور</span></div>{message && <div className="notice">{message}</div>}{created && <div className="invoice-success" role="dialog" aria-modal="true"><div className="invoice-success-card"><span className="success-mark">✓</span><h2>فاکتور {created.number} صادر شد</h2><p>لینک امن فاکتور برای مشتری آماده است و ۳۰ روز اعتبار دارد.</p><input readOnly value={`${window.location.origin}/invoice/${created.publicToken}`} onFocus={(event) => event.currentTarget.select()} /><div><button onClick={() => void navigator.clipboard?.writeText(`${window.location.origin}/invoice/${created.publicToken}`)}>کپی لینک</button><a className="button-primary" target="_blank" rel="noreferrer" href={`/invoice/${created.publicToken}`}>مشاهده فاکتور</a><button className="outline" onClick={() => setCreated(null)}>فاکتور بعدی</button></div></div></div>}
    <div className="cards invoice-form"><div><h2>صدور فاکتور جدید</h2><div className="invoice-product-picker"><input aria-label="جست‌وجوی قلم" placeholder="جست‌وجو با نام، کد یا بارکد..." value={search} onChange={(event) => setSearch(event.target.value)} /><input aria-label="تعداد قلم" type="number" min="1" value={quantity} onChange={(event) => setQuantity(event.target.value)} />{search && <div className="invoice-candidates">{candidates.length ? candidates.map((item) => <button type="button" key={item.id} onClick={() => addLine(item)}><b>{item.product.name}</b><span>{item.brand.name} · {item.product.code} · بارکد {item.barcode}</span><strong>{item.quantity} عدد</strong></button>) : <small>قلم موجودی پیدا نشد.</small>}</div>}</div><div className="invoice-lines">{lines.length ? lines.map((line) => <div className="invoice-line" key={line.item.id}><span><b>{line.item.product.name}</b><small>{line.item.brand.name} · {money(line.item.salePrice)}</small></span><input aria-label={`تعداد ${line.item.product.name}`} type="number" min="1" max={line.item.quantity} value={line.quantity} onChange={(event) => updateLine(line.item.id, event.target.value)} /><strong>{money(Number(line.item.salePrice) * line.quantity)}</strong><button type="button" aria-label="حذف قلم" onClick={() => setLines((current) => current.filter((entry) => entry.item.id !== line.item.id))}>×</button></div>) : <p className="muted">برای شروع، نام یا بارکد قلم را جست‌وجو کنید.</p>}</div><div className="form-grid"><input placeholder="نام مشتری (اختیاری)" value={customer} onChange={(event) => setCustomer(event.target.value)} /><input placeholder="موبایل (اختیاری)" value={mobile} onChange={(event) => setMobile(event.target.value)} /><input type="number" min="0" placeholder="تخفیف ریال" value={discount} onChange={(event) => setDiscount(event.target.value)} /></div><div className="invoice-totals"><span>جمع اقلام: <b>{money(subtotal)}</b></span><span>تخفیف: <b>{money(discountValue)}</b></span><strong>قابل پرداخت: {money(total)}</strong></div><button disabled={!lines.length} onClick={() => void create()}>صدور فاکتور</button></div></div>
    {paying && <div className="notice"><strong>ثبت پرداخت {paying.number}</strong><input type="number" min="1" placeholder="مبلغ پرداختی ریال" value={payAmount} onChange={(event) => setPayAmount(event.target.value)} /><select value={payMethod} onChange={(event) => setPayMethod(event.target.value)}><option value="cash">نقدی</option><option value="card">کارت</option><option value="transfer">واریز</option><option value="credit">اعتباری</option></select><button onClick={() => void pay()}>ثبت</button><button className="outline" onClick={() => setPaying(null)}>انصراف</button></div>}
    <div className="product-table"><div className="table-head invoice-head"><span>شماره</span><span>مشتری</span><span>اقلام</span><span>مبلغ</span><span>پرداخت</span><span>عملیات</span></div>{rows.map((invoice) => <div className="table-row invoice-row" key={invoice.id}><code>{invoice.number}</code><span>{invoice.customerName ?? 'مشتری حضوری'}</span><span>{invoice.items.length}</span><strong>{money(invoice.total)}</strong><span className={invoice.paymentStatus === 'paid' ? 'status-chip' : 'low-stock'}>{labels[invoice.paymentStatus] ?? invoice.paymentStatus}<small> · {money(invoice.paidAmount)}</small></span><span>{invoice.status === 'voided' ? labels.voided : <><button className="row-action" onClick={() => { setPaying(invoice); setPayAmount(String(Number(invoice.total) - Number(invoice.paidAmount))); }}>پرداخت</button> <button className="row-action" onClick={async () => { if (!window.confirm('فاکتور باطل شود؟')) return; try { await api(`/invoices/${invoice.id}/void`, { method: 'POST' }); await load(); } catch (error) { setMessage((error as Error).message); } }}>ابطال</button></>}</span></div>)}</div></section>;
}
