import { useEffect, useState } from 'react';
import { api } from '../lib/api';

type Media = { id: string; path: string; alt?: string; isPrimary: boolean; product?: { id: string; name: string } };
const initial = { productId: '', url: '', alt: '' };

export function MediaPage() {
  const [items, setItems] = useState<Media[]>([]); const [form, setForm] = useState(initial); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const load = () => api<{ data: Media[] }>('/media').then((result) => setItems(result.data)).catch((error: Error) => setMessage(error.message));
  useEffect(() => { void load(); }, []);
  const upload = async () => { if (!form.productId || !file) return setMessage('محصول و فایل تصویر را انتخاب کنید'); const data = new FormData(); data.append('file', file); if (form.alt) data.append('alt', form.alt); setLoading(true); try { await api(`/media/products/${form.productId}/upload`, { method: 'POST', body: data }); setMessage('تصویر با موفقیت آپلود شد'); setFile(null); await load(); } catch (error) { setMessage((error as Error).message); } finally { setLoading(false); } };
  const addUrl = async () => { if (!form.productId || !form.url) return setMessage('محصول و URL تصویر را وارد کنید'); setLoading(true); try { await api(`/media/products/${form.productId}/url`, { method: 'POST', body: JSON.stringify({ url: form.url, alt: form.alt }) }); setMessage('تصویر از URL اضافه شد'); setForm(initial); await load(); } catch (error) { setMessage((error as Error).message); } finally { setLoading(false); } };
  return <section className="media-page"><h1>رسانه‌ها و تصاویر</h1><p className="muted">تصویر را آپلود کنید، از URL اضافه کنید یا از رسانه‌های قبلی انتخاب کنید.</p><div className="media-form"><label>شناسه محصول<input value={form.productId} onChange={(e) => setForm({ ...form, productId: e.target.value })} placeholder="UUID محصول" /></label><label>Alt تصویر<input value={form.alt} onChange={(e) => setForm({ ...form, alt: e.target.value })} placeholder="مثلاً قاب ستون بالای پژو ۲۰۶" /></label><label>آپلود فایل<input type="file" accept="image/*" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></label><button onClick={upload} disabled={loading}>آپلود تصویر</button><label>یا URL تصویر<input value={form.url} onChange={(e) => setForm({ ...form, url: e.target.value })} placeholder="https://..." /></label><button className="outline" onClick={addUrl} disabled={loading}>افزودن URL</button></div>{message && <div className="notice">{message}</div>}<div className="media-grid">{items.map((item) => <article className="media-card" key={item.id}><img src={item.path} alt={item.alt ?? item.product?.name ?? 'تصویر محصول'} /><strong>{item.product?.name ?? 'بدون محصول'}</strong><small>{item.alt ?? 'بدون Alt'}</small><button className="outline" onClick={() => navigator.clipboard.writeText(item.id)}>کپی شناسه رسانه</button></article>)}</div></section>;
}
