import { FormEvent, useEffect, useState } from 'react';
import { api } from '../lib/api';

type Settings = { 'store.profile'?: { name?: string; phones?: string; address?: string; open?: string; close?: string }; 'store.trust_video'?: string; 'sms.templates'?: { invoice?: string; autoSend?: boolean }; 'integrations.telegram'?: { link?: string }; 'inventory.default_min_stock'?: number; 'backup.schedule'?: { enabled?: boolean } };
const initial: Settings = { 'store.profile': { name: '', phones: '', address: '', open: '09:00', close: '20:00' }, 'store.trust_video': '', 'sms.templates': { invoice: '', autoSend: true }, 'integrations.telegram': { link: '' }, 'inventory.default_min_stock': 3, 'backup.schedule': { enabled: true } };
export function SettingsPage() {
  const [settings, setSettings] = useState<Settings>(initial); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { void api<{ data: Settings }>('/settings').then((result) => setSettings({ ...initial, ...result.data })).catch((error: Error) => setMessage(error.message)).finally(() => setLoading(false)); }, []);
  const updateProfile = (key: keyof NonNullable<Settings['store.profile']>, value: string) => setSettings((current) => ({ ...current, 'store.profile': { ...current['store.profile'], [key]: value } }));
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await api('/settings', { method: 'PUT', body: JSON.stringify(settings) }); setMessage('تنظیمات با موفقیت ذخیره شد.'); } catch (error) { setMessage((error as Error).message); } };
  if (loading) return <section><div className="skeleton-block" /><div className="skeleton-block" /></section>;
  return <section className="settings-page"><div className="page-title"><div><span className="eyebrow">مدیریت</span><h1>تنظیمات سیستم</h1><p className="muted">اطلاعات فروشگاه، ارتباطات و سیاست‌های عملیاتی.</p></div><button className="button-primary" form="settings-form">ذخیره تنظیمات</button></div>{message && <div className="notice">{message}</div>}<form id="settings-form" className="settings-grid" onSubmit={submit}><fieldset><legend>اطلاعات فروشگاه</legend><label>نام فروشگاه<input value={settings['store.profile']?.name ?? ''} onChange={(e) => updateProfile('name', e.target.value)} /></label><label>شماره‌های تماس<input value={settings['store.profile']?.phones ?? ''} onChange={(e) => updateProfile('phones', e.target.value)} placeholder="۰۹۱۲...، ۰۴۴..." /></label><label>آدرس<input value={settings['store.profile']?.address ?? ''} onChange={(e) => updateProfile('address', e.target.value)} /></label><div className="two-fields"><label>شروع کار<input type="time" value={settings['store.profile']?.open ?? ''} onChange={(e) => updateProfile('open', e.target.value)} /></label><label>پایان کار<input type="time" value={settings['store.profile']?.close ?? ''} onChange={(e) => updateProfile('close', e.target.value)} /></label></div></fieldset><fieldset><legend>پیامک و ارتباطات</legend><label>قالب فاکتور<textarea value={settings['sms.templates']?.invoice ?? ''} onChange={(e) => setSettings((current) => ({ ...current, 'sms.templates': { ...current['sms.templates'], invoice: e.target.value } }))} placeholder="{نام}، فاکتور {شماره}: {لینک}" rows={3} /></label><label className="switch-row"><input type="checkbox" checked={settings['sms.templates']?.autoSend ?? false} onChange={(e) => setSettings((current) => ({ ...current, 'sms.templates': { ...current['sms.templates'], autoSend: e.target.checked } }))} /> ارسال خودکار لینک فاکتور</label><label>شناسه ویدئوی آپارات<input value={settings['store.trust_video'] ?? ''} onChange={(e) => setSettings((current) => ({ ...current, 'store.trust_video': e.target.value }))} /></label><label>لینک تلگرام<input dir="ltr" value={settings['integrations.telegram']?.link ?? ''} onChange={(e) => setSettings((current) => ({ ...current, 'integrations.telegram': { link: e.target.value } }))} placeholder="https://t.me/..." /></label></fieldset><fieldset><legend>انبار و پشتیبان‌گیری</legend><label>آستانهٔ پیش‌فرض کمبود<input type="number" min="0" value={settings['inventory.default_min_stock'] ?? 0} onChange={(e) => setSettings((current) => ({ ...current, 'inventory.default_min_stock': Number(e.target.value) }))} /></label><label className="switch-row"><input type="checkbox" checked={settings['backup.schedule']?.enabled ?? false} onChange={(e) => setSettings((current) => ({ ...current, 'backup.schedule': { enabled: e.target.checked } }))} /> پشتیبان‌گیری روزانه</label><p className="settings-help">فایل‌های پشتیبان پس از انتقال امن به مقصد خارجی از VPS حذف می‌شوند.</p></fieldset></form></section>;
}
