import { useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';
import { formatRial } from '@salimvand/shared';

type Item = { brand: string; price: string; inStock: boolean };
type Row = { id: string; code: string; name: string; image?: { path: string } | null; category: { id: string; name: string }; vehicles: string[]; price: string; items: Item[] };
const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char] ?? char));
export function WholesalePage() {
  const [rows, setRows] = useState<Row[]>([]); const [q, setQ] = useState(''); const [category, setCategory] = useState(''); const [vehicle, setVehicle] = useState('');
  useEffect(() => { void api<{ data: Row[] }>('/products/wholesale').then((r) => setRows(r.data)); }, []);
  const categories = useMemo(() => [...new Map(rows.map((row) => [row.category.id, row.category])).values()], [rows]);
  const vehicles = useMemo(() => [...new Set(rows.flatMap((row) => row.vehicles))].sort(), [rows]);
  const visible = rows.filter((row) => (!q.trim() || `${row.name} ${row.code}`.includes(q.trim())) && (!category || row.category.id === category) && (!vehicle || row.vehicles.includes(vehicle)));
  const printPdf = () => {
    const date = new Intl.DateTimeFormat('fa-IR', { dateStyle: 'full' }).format(new Date());
    const body = visible.map((row) => `<tr><td>${row.image ? `<img src="${esc(row.image.path)}" alt="">` : '—'}</td><td>${esc(row.code)}</td><td>${esc(row.name)}</td><td>${row.items.map((item) => `${esc(item.brand)} — ${esc(formatRial(Number(item.price)))}`).join('<br>')}</td></tr>`).join('');
    const win = window.open('', '_blank', 'width=1100,height=800'); if (!win) return;
    win.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>لیست محصولات عمده</title><style>@font-face{font-family:Vazirmatn;src:url('${location.origin}/fonts/Vazirmatn-Regular.woff2')}*{box-sizing:border-box}body{font-family:Vazirmatn,Tahoma,sans-serif;color:#17243b;padding:24px}h1{font-size:20px;margin:0 0 5px}p{font-size:11px;color:#68778d;margin:0 0 18px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #ccd5df;padding:8px;text-align:right;vertical-align:middle}th{background:#edf2f7}td:first-child{width:75px;text-align:center}td img{width:60px;height:60px;object-fit:contain} @media print{body{padding:0}}</style></head><body><h1>لیست محصولات (عمده)</h1><p>تاریخ خروجی: ${esc(date)}</p><table><thead><tr><th>تصویر</th><th>کد محصول</th><th>نام محصول</th><th>برند و قیمت</th></tr></thead><tbody>${body}</tbody></table><script>window.onload=()=>{setTimeout(()=>window.print(),300)}</script></body></html>`); win.document.close();
  };
  return <section className="wholesale-page"><div className="page-title"><div><span className="eyebrow">ویژهٔ خریداران عمده</span><h1>لیست محصولات (عمده)</h1><p className="muted">تصویر، کد، برند، قیمت و وضعیت موجودی محصولات</p></div></div><div className="wholesale-filters"><input placeholder="جست‌وجوی نام یا کد محصول" value={q} onChange={(e) => setQ(e.target.value)} /><select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">همه دسته‌ها</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={vehicle} onChange={(e) => setVehicle(e.target.value)}><option value="">همه خودروها</option>{vehicles.map((item) => <option key={item} value={item}>{item}</option>)}</select><button className="button-primary wholesale-print" onClick={printPdf}>خروجی PDF</button></div><div className="wholesale-table-wrap"><table className="wholesale-table"><thead><tr><th>تصویر</th><th>کد محصول</th><th>نام محصول</th><th>برند</th><th>قیمت</th><th>وضعیت</th></tr></thead><tbody>{visible.map((row) => row.items.length ? row.items.map((item) => <tr key={`${row.id}-${item.brand}`}><td rowSpan={row.items.length}>{row.image ? <img src={row.image.path} alt={row.name} /> : '—'}</td><td rowSpan={row.items.length}>{row.code}</td><td rowSpan={row.items.length}>{row.name}</td><td>{item.brand}</td><td>{Number(item.price) > 0 ? formatRial(Number(item.price)) : 'استعلام قیمت'}</td><td className={item.inStock ? 'in-stock' : 'out-stock'}>{item.inStock ? 'موجود' : 'ناموجود'}</td></tr>) : <tr key={row.id}><td>{row.image ? <img src={row.image.path} alt={row.name} /> : '—'}</td><td>{row.code}</td><td>{row.name}</td><td>—</td><td>استعلام قیمت</td><td className="out-stock">ناموجود</td></tr>)}</tbody></table></div></section>;
}
