import { PublicSubHeader } from '../../PublicSubHeader';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
const api = process.env.API_URL ?? 'https://api.salimvand.ir/api/v1';
type Category = { id: string; name: string; slug: string };
type Product = { slug: string; name: string; code: string; availability: string; images: Array<{ path: string; thumbnailPath?: string; alt?: string }>; category: { name: string } };
async function getCategory(slug: string): Promise<{ category: Category; products: Product[] } | null> { try { const filters = await fetch(`${api}/public/filters`, { next: { revalidate: 300 } }); const data = (await filters.json() as { data: { categories: Category[] } }).data; const category = data.categories.find((item) => item.slug === slug); if (!category) return null; const products = await fetch(`${api}/public/products?categoryId=${category.id}`, { next: { revalidate: 300 } }); return { category, products: (await products.json() as { data: Product[] }).data }; } catch { return null; } }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const data = await getCategory((await params).slug); return { title: data ? `${data.category.name} | فروشگاه سلیم وند` : 'دسته‌بندی پیدا نشد', alternates: data ? { canonical: `/category/${data.category.slug}` } : undefined }; }
export default async function CategoryPage({ params }: { params: Promise<{ slug: string }> }) { const data = await getCategory((await params).slug); if (!data) notFound(); const jsonLd = { '@context': 'https://schema.org', '@type': 'CollectionPage', name: data.category.name, url: `https://salimvand.ir/category/${data.category.slug}`, isPartOf: { '@type': 'WebSite', name: 'فروشگاه سلیم وند', url: 'https://salimvand.ir' } }; const breadcrumb = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'خانه', item: 'https://salimvand.ir' }, { '@type': 'ListItem', position: 2, name: data.category.name, item: `https://salimvand.ir/category/${data.category.slug}` }] }; return <main className="shell"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} /><PublicSubHeader context="کاتالوگ قطعات خودرو" /><section className="catalog"><nav className="breadcrumb"><a href="/">خانه</a><span>←</span><span>{data.category.name}</span></nav><p className="eyebrow">دسته‌بندی محصولات</p><h1>{data.category.name}</h1>{data.products.length ? <div className="product-grid">{data.products.map((product) => <a className="product-card" href={`/product/${product.slug}`} key={product.slug}>{product.images[0] ? <img src={product.images[0].thumbnailPath ?? product.images[0].path} srcSet={product.images[0].thumbnailPath ? `${product.images[0].thumbnailPath} 400w, ${product.images[0].path} 900w` : undefined} sizes="(max-width: 620px) 50vw, (max-width: 900px) 33vw, 25vw" alt={product.images[0].alt ?? product.name} loading="lazy" /> : <div className="image-placeholder">قطعه خودرو</div>}<h2>{product.name}</h2><code>{product.code}</code><b className="available">{product.availability === 'in_stock' ? 'موجود' : 'استعلام موجودی'}</b></a>)}</div> : <div className="placeholder">محصولی در این دسته‌بندی ثبت نشده است.</div>}</section></main>; }
