import type { Metadata } from 'next';
import { formatPersianNumber, formatRial } from '@salimvand/shared';

type Props = { params: Promise<{ code: string }> };
type Invoice = { number: string; customerName?: string | null; customerMobile?: string | null; total: string | number; subtotal: string | number; discount: string | number; paidAmount?: string | number; paymentStatus?: string; paymentMethod?: string | null; issuedAt: string; items: Array<{ productName: string; brand?: string; quantity: number; unitPrice: string | number; lineTotal: string | number }> };
export const metadata: Metadata = { title: 'فاکتور آنلاین | فروشگاه سلیم وند', robots: { index: false, follow: false } };
const money = (value: string | number) => formatRial(Number(value));
const statusLabels: Record<string, string> = { paid: 'تسویه شده', partial: 'پرداخت بخشی', unpaid: 'پرداخت نشده' };
const methodLabels: Record<string, string> = { cash: 'نقدی', card: 'کارت‌خوان', transfer: 'واریز بانکی', credit: 'اعتباری' };

export default async function InvoicePage({ params }: Props) {
  const { code } = await params; const api = process.env.API_URL ?? 'https://api.salimvand.ir/api/v1'; let invoice: Invoice | null = null;
  try { const response = await fetch(`${api}/public/invoices/short/${encodeURIComponent(code)}`, { cache: 'no-store' }); if (response.ok) invoice = (await response.json() as { data: Invoice }).data; } catch { invoice = null; }
  if (!invoice) return <main className="invoice-shell"><header className="invoice-header"><span className="brand-mark">س</span><b>فروشگاه سلیم وند</b></header><article className="invoice-card invoice-empty"><span className="invoice-icon">!</span><h1>فاکتور در دسترس نیست</h1><p>این لینک معتبر نیست، منقضی شده یا فاکتور ابطال شده است.</p><a className="button button-primary" href="/">بازگشت به کاتالوگ</a></article></main>;
  const paid = Number(invoice.paidAmount ?? 0); const remaining = Math.max(0, Number(invoice.total) - paid);
  return <main className="invoice-shell"><header className="invoice-header"><a href="/" className="invoice-brand"><span className="brand-mark">س</span><span><b>فروشگاه سلیم وند</b><small>آذین خودرو · میاندوآب</small></span></a><div className="invoice-actions"><button onClick={() => typeof window !== 'undefined' && window.print()}>چاپ</button><a href={`${api}/public/invoices/short/${encodeURIComponent(code)}/pdf`} target="_blank" rel="noreferrer">دانلود PDF</a></div></header><article className="invoice-card"><div className="invoice-title"><div><span className="eyebrow">سند فروش آنلاین</span><h1>فاکتور {invoice.number}</h1><p>تاریخ صدور: {new Intl.DateTimeFormat('fa-IR').format(new Date(invoice.issuedAt))}</p></div><span className={`invoice-status ${invoice.paymentStatus ?? 'unpaid'}`}>{statusLabels[invoice.paymentStatus ?? 'unpaid'] ?? invoice.paymentStatus}</span></div><div className="invoice-meta"><div><small>مشتری</small><b>{invoice.customerName ?? 'مشتری حضوری'}</b></div>{invoice.customerMobile && <div><small>شماره تماس</small><b dir="ltr">{invoice.customerMobile}</b></div>}<div><small>اعتبار لینک</small><b>۳۰ روز</b></div></div><h2 className="invoice-section-title">اقلام فاکتور <small>{formatPersianNumber(invoice.items.length)} قلم</small></h2><div className="invoice-items"><div className="invoice-item-head"><span>شرح کالا</span><span>تعداد</span><span>فی (ریال)</span><span>جمع</span></div>{invoice.items.map((item, index) => <div className="invoice-item" key={`${item.productName}-${index}`}><strong>{item.productName}{item.brand && <small className="invoice-item-brand"> · {item.brand}</small>}</strong><span>{formatPersianNumber(item.quantity)}</span><span>{money(item.unitPrice)}</span><b>{money(item.lineTotal)}</b></div>)}</div><div className="invoice-summary"><div><span>جمع اقلام</span><b>{money(invoice.subtotal)}</b></div><div><span>تخفیف</span><b>− {money(invoice.discount)}</b></div><div className="invoice-total"><span>مبلغ قابل پرداخت</span><strong>{money(invoice.total)}</strong></div><div className="invoice-paid"><span>پرداخت‌شده</span><b>{money(paid)}</b></div>{invoice.paymentMethod && <div className="invoice-paid"><span>روش پرداخت</span><b>{methodLabels[invoice.paymentMethod] ?? invoice.paymentMethod}</b></div>}<div className="invoice-remaining"><span>باقی‌مانده</span><b>{money(remaining)}</b></div></div><p className="invoice-note">این صفحه فقط اطلاعات عمومی فاکتور را نمایش می‌دهد و هیچ اطلاعات داخلی انبار، قیمت خرید یا قفسه در آن وجود ندارد.</p></article><footer className="invoice-footer">برای پیگیری یا پرداخت با فروشگاه سلیم وند تماس بگیرید · قیمت نهایی هنگام صدور فاکتور قطعی است.</footer></main>;
}
