import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma.service';
import { writeAudit } from '../../common/audit/audit-log';

@Injectable()
export class CustomersService {
  constructor(private readonly prisma: PrismaService) {}
  async list(search?: string) { const q = search?.trim(); const customers = await this.prisma.customer.findMany({ where: { isActive: true, ...(q ? { OR: [{ name: { contains: q, mode: 'insensitive' } }, { mobile: { contains: q } }] } : {}) }, orderBy: { createdAt: 'desc' }, take: 100, include: { invoices: { where: { status: 'issued' }, select: { total: true, paidAmount: true } } } }); return { ok: true, data: customers.map((customer) => ({ ...customer, debt: customer.invoices.reduce((sum, invoice) => sum + invoice.total - invoice.paidAmount, 0n), invoiceCount: customer.invoices.length, invoices: undefined })) }; }
  async get(id: string) { const customer = await this.prisma.customer.findFirst({ where: { id, isActive: true }, include: { invoices: { orderBy: { issuedAt: 'desc' }, include: { items: true } } } }); if (!customer) throw new NotFoundException('مشتری پیدا نشد'); return { ok: true, data: { ...customer, debt: customer.invoices.filter((item) => item.status === 'issued').reduce((sum, invoice) => sum + invoice.total - invoice.paidAmount, 0n) } }; }
  async create(input: { name?: string; mobile?: string; notes?: string }, actorId?: string, ip?: string) { const name = input.name?.trim(); const mobile = input.mobile?.trim(); if (!name || !mobile || !/^09\d{9}$/.test(mobile)) throw new BadRequestException('نام و شماره موبایل معتبر الزامی است'); const customer = await this.prisma.customer.create({ data: { name, mobile, notes: input.notes?.trim() || undefined } }); if (actorId) await writeAudit(this.prisma, { userId: actorId, ip, action: 'create', entityType: 'customer', entityId: customer.id, after: { name, mobile } }); return { ok: true, data: customer }; }
  async update(id: string, input: { name?: string; mobile?: string; notes?: string; isActive?: boolean }, actorId?: string, ip?: string) { const before = await this.prisma.customer.findUnique({ where: { id } }); if (!before) throw new NotFoundException('مشتری پیدا نشد'); const data: Prisma.CustomerUpdateInput = {}; if (input.name?.trim()) data.name = input.name.trim(); if (input.mobile !== undefined) { if (!/^09\d{9}$/.test(input.mobile)) throw new BadRequestException('شماره موبایل معتبر نیست'); data.mobile = input.mobile; } if (input.notes !== undefined) data.notes = input.notes.trim() || null; if (input.isActive !== undefined) data.isActive = input.isActive; const customer = await this.prisma.customer.update({ where: { id }, data }); if (actorId) await writeAudit(this.prisma, { userId: actorId, ip, action: input.isActive === false ? 'delete' : 'update', entityType: 'customer', entityId: id, before: { name: before.name, isActive: before.isActive }, after: { name: customer.name, isActive: customer.isActive } }); return { ok: true, data: customer }; }
  async payment(id: string, input: { amount?: string | number; method?: string; invoiceId?: string; notes?: string }, actorId: string, ip?: string) {
    const amount = BigInt(input.amount ?? 0); const methods = new Set(['cash', 'card', 'transfer', 'credit']);
    if (amount <= 0n || !input.method || !methods.has(input.method)) throw new BadRequestException('مبلغ مثبت و روش پرداخت معتبر الزامی است');
    const customer = await this.prisma.customer.findFirst({ where: { id, isActive: true } }); if (!customer) throw new NotFoundException('مشتری پیدا نشد');
    const payment = await this.prisma.customerPayment.create({ data: { customerId: id, invoiceId: input.invoiceId || undefined, amount, method: input.method as never, notes: input.notes?.trim() || undefined, receivedById: actorId } });
    await writeAudit(this.prisma, { userId: actorId, ip, action: 'pay', entityType: 'customer', entityId: id, after: { amount: amount.toString(), method: input.method } }); return { ok: true, data: payment };
  }

  async debtors() { const customers = await this.prisma.customer.findMany({ where: { isActive: true }, include: { invoices: { where: { status: 'issued', paymentStatus: { in: ['unpaid', 'partial'] } }, select: { total: true, paidAmount: true } } } }); return { ok: true, data: customers.map((customer) => ({ id: customer.id, name: customer.name, mobile: customer.mobile, debt: customer.invoices.reduce((sum, invoice) => sum + invoice.total - invoice.paidAmount, 0n), invoiceCount: customer.invoices.length })).filter((customer) => customer.debt > 0n).sort((a, b) => (a.debt > b.debt ? -1 : 1)) }; }
}
