import { describe, expect, it, vi } from 'vitest';
import { CatalogAdminService } from './catalog-admin.service';

function makeService() { const prisma = { product: { create: vi.fn(), update: vi.fn(), findFirst: vi.fn() }, counter: { upsert: vi.fn().mockResolvedValue({ lastValue: 12 }) } }; return { service: new CatalogAdminService(prisma as never), prisma }; }

describe('CatalogAdminService', () => {
  it('generates a stable slug and accepts manual SEO on create', async () => { const { service, prisma } = makeService(); prisma.product.create.mockResolvedValue({ id: 'p1' }); const result = await service.create({ name: 'قاب ستون پژو ۲۰۶', categoryId: 'c1', slug: 'ghab-sotun-206', seoTitle: 'عنوان اختصاصی', seoDescription: 'توضیح اختصاصی' }); expect(result).toEqual({ ok: true, data: { id: 'p1' } }); expect(prisma.product.create).toHaveBeenCalledWith({ data: expect.objectContaining({ code: 'PRODUCT-00012', slug: 'ghab-sotun-206', seoTitle: 'عنوان اختصاصی', seoDescription: 'توضیح اختصاصی' }) }); });
  it('does not overwrite manual SEO when the product name changes', async () => { const { service, prisma } = makeService(); prisma.product.findFirst.mockResolvedValue({ id: 'p1' }); prisma.product.update.mockResolvedValue({ id: 'p1' }); await service.update('p1', { name: 'نام جدید', seoTitle: 'عنوان مدیر', seoDescription: 'توضیح مدیر', slug: 'custom-slug' }); expect(prisma.product.update).toHaveBeenCalledWith({ where: { id: 'p1' }, data: expect.objectContaining({ name: 'نام جدید', seoTitle: 'عنوان مدیر', seoDescription: 'توضیح مدیر', slug: 'custom-slug' }) }); });
  it('soft deletes and restores products without physically removing them', async () => { const { service, prisma } = makeService(); prisma.product.findFirst.mockResolvedValue({ id: 'p1' }); prisma.product.update.mockResolvedValue({ id: 'p1', status: 'hidden' }); await service.softDelete('p1'); expect(prisma.product.update).toHaveBeenCalledWith({ where: { id: 'p1' }, data: { deletedAt: expect.any(Date), status: 'hidden' } }); prisma.product.update.mockResolvedValue({ id: 'p1', status: 'active', deletedAt: null }); await service.restore('p1'); expect(prisma.product.update).toHaveBeenLastCalledWith({ where: { id: 'p1' }, data: { deletedAt: null, status: 'active' } }); });

});
