import { APP_NAME, STORE_BRAND } from '@salimvand/shared';

const apiUrl = process.env.API_URL ?? 'https://api.salimvand.ir/api/v1';
type Product = { slug: string; name: string; code: string; availability: string; brands: Array<{ name: string; inStock: boolean }>; images: Array<{ path: string; alt?: string }>; category: { name: string } };
type Filter = { id: string; name: string; slug?: string };
async function getProducts(query: string): Promise<{ items: Product[]; totalPages: number; page: number }> { try { const response = await fetch(`${apiUrl}/public/products${query ? `?${query}` : ''}`, { next: { revalidate: 300 } }); if (!response.ok) return { items: [], totalPages: 0, page: 1 }; const body = await response.json() as { data: Product[]; meta?: { totalPages?: number; page?: number } }; return { items: body.data, totalPages: body.meta?.totalPages ?? 1, page: body.meta?.page ?? 1 }; } catch { return { items: [], totalPages: 0, page: 1 }; } }
async function getFilters(): Promise<{ categories: Filter[]; brands: Filter[]; vehicles: Array<{ id: string; name: string; models: Array<{ id: string; name: string }> }> }> { try { const response = await fetch(`${apiUrl}/public/filters`, { next: { revalidate: 300 } }); if (!response.ok) return { categories: [], brands: [], vehicles: [] }; return (await response.json() as { data: { categories: Filter[]; brands: Filter[]; vehicles: Array<{ id: string; name: string; models: Array<{ id: string; name: string }> }> } }).data; } catch { return { categories: [], brands: [], vehicles: [] }; } }

export async function generateMetadata({ searchParams }: { searchParams: Promise<{ q?: string; categoryId?: string; vehicleModelId?: string; brandId?: string; inStock?: string }> }) {
  const params = await searchParams;
  const filtered = Object.values(params).some(Boolean);
  return { title: filtered ? 'جستجوی قطعات خودرو | فروشگاه سلیم وند' : 'فروشگاه سلیم وند | آذین خودرو میاندوآب', description: 'فروش لوازم داخلی و لوازم داخل کابین خودرو در میاندوآب، آذربایجان غربی.', robots: filtered ? { index: false, follow: true } : { index: true, follow: true } };
}

export default async function HomePage({ searchParams }: { searchParams: Promise<{ q?: string; categoryId?: string; vehicleModelId?: string; brandId?: string; inStock?: string; page?: string }> }) {
  const params = await searchParams; const query = new URLSearchParams(); if (params.q) query.set('q', params.q); if (params.categoryId) query.set('categoryId', params.categoryId); if (params.vehicleModelId) query.set('vehicleModelId', params.vehicleModelId); if (params.brandId) query.set('brandId', params.brandId); if (params.page) query.set('page', params.page); if (params.inStock === 'true') query.set('inStock', 'true'); const [products, filters] = await Promise.all([getProducts(query.toString()), getFilters()]);
  return <main className="shell"><header><strong>{APP_NAME}</strong><span>آذین خودرو · میاندوآب</span></header><section className="hero"><p className="eyebrow">{STORE_BRAND}</p><h1>لوازم داخلی و قطعات خودروهای داخلی</h1><p>کاتالوگ آنلاین قطعات کابین و لوازم خودرو در شهرستان میاندوآب، آذربایجان غربی. قطعهٔ موردنظر را پیدا کنید و برای استعلام قیمت با ما تماس بگیرید.</p><button>مشاهده کاتالوگ</button></section><section className="catalog"><div className="section-title"><div><p className="eyebrow">کاتالوگ محصولات</p><h2>قطعات و لوازم داخل کابین خودرو</h2></div><span>قیمت فقط با استعلام</span></div><form className="filters" method="get"><input name="q" defaultValue={params.q} placeholder="جستجوی نام قطعه یا شماره فنی" /><select name="categoryId" defaultValue={params.categoryId ?? ''}><option value="">همه دسته‌ها</option>{filters.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="brandId" defaultValue={params.brandId ?? ''}><option value="">همه برندها</option>{filters.brands.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="vehicleModelId" defaultValue={params.vehicleModelId ?? ''}><option value="">همه خودروها</option>{filters.vehicles.flatMap((make) => make.models.map((model) => <option key={model.id} value={model.id}>{make.name} - {model.name}</option>))}</select><label><input type="checkbox" name="inStock" value="true" defaultChecked={params.inStock === 'true'} /> فقط موجود</label><button type="submit">جستجو</button><a href="/">پاک کردن</a></form>{products.items.length ? <div className="product-grid">{products.items.map((product) => <a className="product-card" href={`/product/${product.slug}`} key={product.slug}>{product.images[0] ? <img src={product.images[0].path} alt={product.images[0].alt ?? product.name} /> : <div className="image-placeholder">قطعه خودرو</div>}<small>{product.category.name}</small><h3>{product.name}</h3><code>{product.code}</code><b className={product.availability === 'in_stock' ? 'available' : 'unavailable'}>{product.availability === 'in_stock' ? 'موجود' : 'استعلام موجودی'}</b></a>)}</div> : <div className="placeholder">محصولی با این فیلترها پیدا نشد.</div>}{products.totalPages > 1 && <nav className="pagination">{Array.from({ length: products.totalPages }, (_, index) => { const page = index + 1; const next = new URLSearchParams(query.toString()); next.set('page', String(page)); return <a className={products.page === page ? 'current' : ''} href={`/?${next.toString()}`} key={page}>{page}</a>; })}</nav>}</section><section className="local-seo"><h2>فروش لوازم داخلی خودرو در میاندوآب</h2><p>فروشگاه سلیم وند و آذین خودرو، ارائه‌دهندهٔ لوازم داخل کابین و قطعات خودروهای داخلی در میاندوآب و آذربایجان غربی است. برای اطلاع از موجودی برندها و استعلام قیمت با فروشگاه تماس بگیرید.</p></section><footer>{STORE_BRAND} · شهرستان میاندوآب، آذربایجان غربی</footer></main>;
}
